In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [6, -3, -6, 3],
    [-42, 27, 44, -14],
    [-6, 15, 4, 8],
    [12, -42, -42, -52]
  ])

b = np.array([
    [93],
    [-631],
    [-23],
    [128]
  ])

A = np.concatenate((A, b), axis=1)
print("Matriz:\n", A)
print()

def decomposicaoLU(A):
  length = len(A)
  L = np.eye(length) # matriz identidade

  for i in range(length):
    pivo = A[i, i]

    for j in range(i+1, length):
      fator = A[j, i] / pivo

      L[j, i] = fator
      A[j] = A[j] - (fator * A[i])

  U = A[:, :-1] # A, sem a última coluna (que é b)
  return L, U

L, U = decomposicaoLU(A)
print("Matriz L:\n", L)
print()
print("Matriz U:\n", U)

Matriz:
 [[   6   -3   -6    3   93]
 [ -42   27   44  -14 -631]
 [  -6   15    4    8  -23]
 [  12  -42  -42  -52  128]]

Matriz L:
 [[ 1.  0.  0.  0.]
 [-7.  1.  0.  0.]
 [-1.  2.  1.  0.]
 [ 2. -6.  3.  1.]]

Matriz U:
 [[ 6 -3 -6  3]
 [ 0  6  2  7]
 [ 0  0 -6 -3]
 [ 0  0  0 -7]]
