In [ ]:
import numpy as np

In [ ]:
# matriz 3x3
A = np.array([
    [-6, -2, -3],
    [-36, -19, -24],
    [6, 30, 34]
  ])

b = np.array([
    [17],
    [97],
    [-32]
  ])

# matriz aumentada
A = np.concatenate((A, b), axis=1)
print("Matriz:\n", A)

# Escalonamento
pivo = A[0, 0]

fator = A[1, 0] / pivo
A[1, :] = A[1, :] - fator * A[0, :]
print(f"\nFator L2 = L2 - ({fator}) * L1")

fator = A[2, 0] / pivo
A[2, :] = A[2, :] - fator * A[0, :]
print(f"Fator L3 = L3 - ({fator}) * L1")

pivo = A[1, 1]

fator = A[2, 1] / pivo
A[2, :] = A[2, :] - fator * A[1, :]
print(f"Fator L3 = L3 - ({fator}) * L2")

print("\nMatriz Escalonada:\n", A)

Matriz:
 [[ -6  -2  -3  17]
 [-36 -19 -24  97]
 [  6  30  34 -32]]

Fator L2 = L2 - (6.0) * L1
Fator L3 = L3 - (-1.0) * L1
Fator L3 = L3 - (-4.0) * L2

Matriz Escalonada:
 [[ -6  -2  -3  17]
 [  0  -7  -6  -5]
 [  0   0   7 -35]]


In [ ]:
# matriz 4x4
A = np.array([
    [7, 1, 3, 1],
    [35, -2, 14, 8],
    [35, -30, 6, 27],
    [28, -38, -2, 39]
  ])

b = np.array([
    [-40],
    [-225],
    [-259],
    [-160]
  ])

# matriz aumentada
A = np.concatenate((A, b), axis=1)
print("Matriz:\n", A)

pivo = A[0, 0]
fator = A[1, 0] / pivo
A[1, :] = A[1, :] - fator * A[0, :]
print(f"\n{fator}")

fator = A[2, 0] / pivo
A[2, :] = A[2, :] - fator * A[0, :]
print(fator)

fator = A[3, 0] / pivo
A[3, :] = A[3, :] - fator * A[0, :]
print(fator)

pivo = A[1, 1]
fator = A[2, 1] / pivo
A[2, :] = A[2, :] - fator * A[1, :]
print(fator)

fator = A[3, 1] / pivo
A[3, :] = A[3, :] - fator * A[1, :]
print(fator)

pivo = A[2, 2]
fator = A[3, 2] / pivo
A[3, :] = A[3, :] - fator * A[2, :]

print("\nMatriz Escalonada:\n", A)

Matriz:
 [[   7    1    3    1  -40]
 [  35   -2   14    8 -225]
 [  35  -30    6   27 -259]
 [  28  -38   -2   39 -160]]

5.0
5.0
4.0
5.0
6.0

Matriz Escalonada:
 [[  7   1   3   1 -40]
 [  0  -7  -1   3 -25]
 [  0   0  -4   7  66]
 [  0   0   0   3  18]]


In [ ]:
A = np.array([
    [7, 1, 3, 1],
    [35, -2, 14, 8],
    [35, -30, 6, 27],
    [28, -38, -2, 39]
  ])

b = np.array([
    [-40],
    [-225],
    [-259],
    [-160]
  ])

A = np.concatenate((A, b), axis=1)
print("Matriz:\n", A)
print()

# Método de Gauss-Jordan
def gauss(A, b):
  length = len(A)

  for i in range(length):
    pivo = A[i, i]

    for j in range(i + 1, length):
      fator = A[j, i] / pivo
      print(f"Fator L{j + 1} = L{j + 1} - ({fator}) * L{i + 1}")

      A[j, :] = A[j, :] - fator * A[i, :]
      b[j] = b[j] - fator * b[i]

  return A

A = gauss(A, b)
print("\nMatriz Escalonada:\n", A)

Matriz:
 [[   7    1    3    1  -40]
 [  35   -2   14    8 -225]
 [  35  -30    6   27 -259]
 [  28  -38   -2   39 -160]]

Fator L2 = L2 - (5.0) * L1
Fator L3 = L3 - (5.0) * L1
Fator L4 = L4 - (4.0) * L1
Fator L3 = L3 - (5.0) * L2
Fator L4 = L4 - (6.0) * L2
Fator L4 = L4 - (2.0) * L3

Matriz Escalonada:
 [[  7   1   3   1 -40]
 [  0  -7  -1   3 -25]
 [  0   0  -4   7  66]
 [  0   0   0   3  18]]
