# Sistemas Lineares

Um Sistema Linear é um conjunto finito de equações lineares de n variáveis, onde pode ser um sistema:

- Determinado (uma solução)
- Indeterminado (mais de uma solução)
- Impossível (nenhuma solução)

Para resolução numérica de sistemas, podemos escreve-lós na sua forma matricial e utilizar métodos númericos:

- Direto: Gauss; Decomposição LU
- Interativo: Jacobi; Gauss-Seidel

## Importações

In [1]:
import numpy as np

## Substituição Sucessiva

A substituição sucessiva é usada para resolver sistemas com uma matriz triangular inferior.

In [23]:
A = np.array([
    [2, 0, 0],
    [1, 2, 0],
    [2, 4, 1]
])

b = np.array([1, -2, -12])

def substituicao_sucessiva(A, b):
    x = np.zeros(len(b))

    # Substituição regressiva
    for i in range(len(b)):
        x[i] = b[i]
        for j in range(i):
            x[i] -= A[i, j] * x[j]
        x[i] /= A[i, i]
    return x

x = substituicao_sucessiva(A, b)

print("Matriz A:\n", A)
print("\nMatriz b:\n", b)
print("\nMatriz x:\n", x)

Matriz A:
 [[2 0 0]
 [1 2 0]
 [2 4 1]]

Matriz b:
 [  1  -2 -12]

Matriz x:
 [ 0.5  -1.25 -8.  ]


## Resolução Retroativa

A resolução retroativa é usada para resolver sistemas com uma matriz triangular superior.

In [22]:
A = np.array([
    [1, 1, 2],
    [0, 2, 1],
    [0, 0, 5]
])

b = np.array([1, -3, -5])

def resolucao_retroativa(A, b):
    x = np.zeros(len(b))

    # Substituição regressiva
    for i in range(len(b) - 1, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, len(b)):
            x[i] -= A[i, j] * x[j]
        x[i] /= A[i, i]
    return x

x = resolucao_retroativa(A, b)

print("Matriz A:\n", A)
print("\nMatriz b:\n", b)
print("\nMatriz x:\n", x)

Matriz A:
 [[1 1 2]
 [0 2 1]
 [0 0 5]]

Matriz b:
 [ 1 -3 -5]

Matriz x:
 [ 4. -1. -1.]


## Método de Gauss (Eliminação Gaussiana)

O método de Gauss utiliza transformações elementares para encontrar uma matriz triangular equivalente.

In [3]:
A = np.array([
    [7, 1, 3, 1],
    [35, -2, 14, 8],
    [35, -30, 6, 27],
    [28, -38, -2, 39]
  ])

b = np.array([
    [-40],
    [-225],
    [-259],
    [-160]
  ])

A = np.concatenate((A, b), axis=1)
print("Matriz Aumentada:\n", A, "\n")

def gauss(A, b):
  for i in range(len(A)):
    pivo = A[i, i]

    for j in range(i + 1, len(A)):
      fator = A[j, i] / pivo
      print(f"Fator L{j + 1} = L{j + 1} - ({fator}) * L{i + 1}")

      A[j, :] = A[j, :] - fator * A[i, :]
      b[j] = b[j] - fator * b[i]

  return A

A = gauss(A, b)
print("\nMatriz Escalonada:\n", A)

Matriz Aumentada:
 [[   7    1    3    1  -40]
 [  35   -2   14    8 -225]
 [  35  -30    6   27 -259]
 [  28  -38   -2   39 -160]] 

Fator L2 = L2 - (5.0) * L1
Fator L3 = L3 - (5.0) * L1
Fator L4 = L4 - (4.0) * L1
Fator L3 = L3 - (5.0) * L2
Fator L4 = L4 - (6.0) * L2
Fator L4 = L4 - (2.0) * L3

Matriz Escalonada:
 [[  7   1   3   1 -40]
 [  0  -7  -1   3 -25]
 [  0   0  -4   7  66]
 [  0   0   0   3  18]]


## Método da Decomposição LU

A decomposição LU fatora uma matriz em duas matrizes triangulares, uma inferior e outra superior.

In [4]:
A = np.array([
    [6, -3, -6, 3],
    [-42, 27, 44, -14],
    [-6, 15, 4, 8],
    [12, -42, -42, -52]
  ])

b = np.array([
    [93],
    [-631],
    [-23],
    [128]
  ])

A = np.concatenate((A, b), axis=1)
print("Matriz Aumentada:\n", A, "\n")

def decomposicaoLU(A):
  L = np.eye(len(A)) # matriz identidade

  for i in range(len(A)):
    pivo = A[i, i]

    for j in range(i+1, len(A)):
      fator = A[j, i] / pivo

      L[j, i] = fator
      A[j] = A[j] - (fator * A[i])

  U = A[:, :-1] # A, sem a última coluna (que é b)
  return L, U

L, U = decomposicaoLU(A)
print("Matriz L:\n", L)
print("\nMatriz U:\n", U)

Matriz Aumentada:
 [[   6   -3   -6    3   93]
 [ -42   27   44  -14 -631]
 [  -6   15    4    8  -23]
 [  12  -42  -42  -52  128]] 

Matriz L:
 [[ 1.  0.  0.  0.]
 [-7.  1.  0.  0.]
 [-1.  2.  1.  0.]
 [ 2. -6.  3.  1.]]

Matriz U:
 [[ 6 -3 -6  3]
 [ 0  6  2  7]
 [ 0  0 -6 -3]
 [ 0  0  0 -7]]


## Método de Jacobi

O método de Jacobi utiliza uma aproximação inicial e a cada interação filtra um resultado melhor de acordo com as aproximações anteriores.

In [12]:
A = np.array([
    [-4, 5, 2],
    [-8, 9, 1],
    [-4, 9, 17]
  ])

b = np.array([
    [23],
    [50],
    [-2]
  ])

print("Matriz A:\n", A)
print("\nMatriz b:\n", b, "\n")

def jacobi(A, b, erro, itMax):
  xOld = np.zeros((len(A), 1)) # Inicializar xOld com zeros

  D_inv = np.linalg.inv(np.diag(np.diag(A))) # Inversa da matriz diagonal
  B = -D_inv @ (A - np.diag(np.diag(A))) # Matriz B
  d = D_inv @ b # Calculando d

  it = 0
  er = 1 # erro relativo

  while er >= erro and it < itMax:
    x = B @ xOld + d
    er = np.max(np.abs(x - xOld)) / np.max(np.abs(x))
    xOld = x
    it += 1

  return x, er, it

x, er, it = jacobi(A, b, 10 ** -2, 4)
print("Matriz aproximada:\n", x)
print("\nErro relativo: ", er)
print("Número de interações: ", it)

Matriz A:
 [[-4  5  2]
 [-8  9  1]
 [-4  9 17]]

Matriz b:
 [[23]
 [50]
 [-2]] 

Matriz aproximada:
 [[ 3.02266222]
 [-0.99769319]
 [-5.59015763]]

Erro relativo:  1.861602093840746
Número de interações:  4


## Método de Gauss-Seidel

Diferente do método de Jacobi, Gauss-Seidel intera sobre cada aproximação e opera imediatamente os novos valores.

In [14]:
A = np.array([
    [12, 2, -1],
    [3, 12, 2],
    [4, 3, -17]
  ])

b = np.array([
    [7],
    [12],
    [-1]
  ])

print("Matriz A:\n", A)
print("\nMatriz b:\n", b, "\n")

def gaussSeidel(A, b, erro, itMax):
  x = np.zeros((len(A), 1))

  it = 0
  er = 1

  while er >= erro and it < itMax:
    xOld = x.copy()

    for i in range(len(A)):
      soma1 = np.dot(A[i, :i], x[:i])
      soma2 = np.dot(A[i, i+1:], xOld[i+1:])
      x[i] = (b[i] - soma1 - soma2) / A[i, i]

    er = np.max(np.abs(x - xOld)) / np.max(np.abs(x))
    it += 1

  return x, er, it

x, er, it = gaussSeidel(A, b, 10 ** -4, 3)
print("Matriz aproximada:\n", x)
print("\nErro relativo: ", er)
print("Número de interações: ", it)

Matriz A:
 [[ 12   2  -1]
 [  3  12   2]
 [  4   3 -17]]

Matriz b:
 [[ 7]
 [12]
 [-1]] 

Matriz aproximada:
 [[0.47212198]
 [0.82948243]
 [0.31629031]]

Erro relativo:  0.005730152670416939
Número de interações:  3
